/// Regenerate `lib/src/widgets.g.dart` -- which exported Flutter names are `Widget`
/// subclasses, and which are not.
///
/// WHY A GENERATED TABLE.
///
/// `branches.dart` counts, per arm of a conditional, how many non-const widgets the arm
/// instantiates. "Is this a widget?" is a resolved question and `dart_tools` is parse-only
/// at run time, for the reason `export_namespaces.dart` states: a mined transplant does not
/// resolve. So the question is answered HERE, once, against a project that does resolve
/// Flutter, and shipped as a constant.
///
/// Without it the count is the old regex's count: every capitalised identifier followed by
/// `(`. Measured on one real transplant that put `TextStyle`, `EdgeInsets`, `Color`,
/// `BoxDecoration`, `BorderRadius` and `InputDecoration` into a "widget" count -- 13 of 28
/// matches were not widgets. The feature schema separates exactly these as
/// `valueObjectAllocCount`, so conflating them measures a different quantity than the one
/// the rule claims to maximise.
///
/// A name absent from BOTH sets is `unknown`, never assumed to be a widget: user-defined
/// types cannot be classified without resolving the transplant, and `branches.dart` reports
/// them rather than guessing.
///
/// Usage (from `scripts/dart_tools/`):
///
///     dart run tool/export_widgets.dart <resolvable-project-root> > lib/src/widgets.g.dart
///
/// The root must be a project whose `package_config.json` resolves Flutter --
/// `benchmark_container` itself does. Re-run after a Flutter SDK upgrade.
library;

import 'dart:io';

import 'package:analyzer/dart/analysis/analysis_context_collection.dart';
import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/element/element.dart';

/// The libraries a transplant can name a widget from. Deliberately the widget-bearing
/// subset of `export_namespaces.libraries`: `dart:math` defines no widgets and scanning it
/// only risks a name collision.
const libraries = <String>[
  'package:flutter/material.dart',
  'package:flutter/cupertino.dart',
  'package:flutter/widgets.dart',
  'package:flutter/painting.dart',
  'package:flutter/rendering.dart',
  'package:flutter/foundation.dart',
  'package:flutter/gestures.dart',
  'package:flutter/animation.dart',
  'package:flutter/services.dart',
];

Future<void> main(List<String> args) async {
  if (args.isEmpty) {
    stderr.writeln('usage: dart run tool/export_widgets.dart <project-root>');
    exitCode = 2;
    return;
  }
  final root = File(args.first).absolute.path;
  final collection = AnalysisContextCollection(includedPaths: [root]);
  final session = collection.contextFor(root).currentSession;

  final widgets = <String>{};
  final nonWidgets = <String>{};

  for (final uri in libraries) {
    final result = await session.getLibraryByUri(uri);
    if (result is! LibraryElementResult) {
      stderr.writeln('SKIPPED $uri -> ${result.runtimeType}');
      continue;
    }
    for (final entry in result.element.exportNamespace.definedNames2.entries) {
      final name = entry.key;
      if (!RegExp(r'^[A-Z][A-Za-z0-9_$]*$').hasMatch(name)) continue;
      final element = entry.value;
      if (element is! InterfaceElement) continue;
      final isWidget = element.name == 'Widget' ||
          element.allSupertypes.any((t) => t.element.name == 'Widget');
      (isWidget ? widgets : nonWidgets).add(name);
    }
  }

  // A name that is a widget in one library and not in another cannot be classified from a
  // bare identifier, so it is neither. None exist today; the guard is here so that a future
  // Flutter release introducing one degrades to `unknown` rather than to a silent verdict.
  final ambiguous = widgets.intersection(nonWidgets);
  for (final name in ambiguous) {
    stderr.writeln('AMBIGUOUS (dropped to unknown): $name');
  }
  widgets.removeAll(ambiguous);
  nonWidgets.removeAll(ambiguous);

  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/export_widgets.dart -- do not edit by hand.')
    ..writeln('//')
    ..writeln('// Dart SDK ${Platform.version.split(' ').first}. Regenerate after an SDK or')
    ..writeln('// Flutter upgrade. A name in NEITHER set is `unknown` and is reported, never')
    ..writeln('// counted as a widget, so a stale table loses precision and never invents a')
    ..writeln('// verdict.')
    ..writeln('library;')
    ..writeln()
    ..writeln('/// Exported Flutter names whose class is a `Widget` subtype.')
    ..writeln('const kWidgetNames = <String>{');
  for (final name in widgets.toList()..sort()) {
    buffer.writeln("  '$name',");
  }
  buffer
    ..writeln('};')
    ..writeln()
    ..writeln('/// Exported Flutter names that are classes but NOT widgets -- `TextStyle`,')
    ..writeln('/// `EdgeInsets`, `BoxDecoration`. The feature schema counts these as')
    ..writeln('/// `valueObjectAllocCount`, a different quantity from the widget count.')
    ..writeln('const kNonWidgetNames = <String>{');
  for (final name in nonWidgets.toList()..sort()) {
    buffer.writeln("  '$name',");
  }
  buffer.writeln('};');
  stdout.write(buffer);

  stderr.writeln('widgets: ${widgets.length}, non-widgets: ${nonWidgets.length}');
}
