/// Regenerate `lib/src/namespaces.g.dart` -- the exported top-level name set of every
/// library the corpus imports.
///
/// WHY A GENERATED TABLE.
///
/// The export-time rule needs to know whether one import's names are covered by another's.
/// That is a resolved question, but only about SDK libraries -- never about the transplant.
/// Resolving it here, once, keeps `dart_tools` parse-only at run time, which matters
/// because a mined transplant does not resolve: it has no `dependencies.dart` yet, so it
/// carries error-severity diagnostics, and the analyzer suppresses `unused_import` and
/// `unnecessary_import` entirely on any file that has an error. Asking the analyzer about
/// the transplants directly reports nothing at all -- measured: 19 of 20 real transplants
/// have errors, and the 20th produced all 7 of the run's diagnostics.
///
/// Usage (from `scripts/dart_tools/`):
///
///     dart run tool/export_namespaces.dart <resolvable-project-root> > lib/src/namespaces.g.dart
///
/// The root must be a project whose `package_config.json` resolves Flutter --
/// `benchmark_container` itself does. Re-run after a Flutter SDK upgrade; the table records
/// the SDK version it came from so drift is visible.
library;

import 'dart:io';

import 'package:analyzer/dart/analysis/analysis_context_collection.dart';
import 'package:analyzer/dart/analysis/results.dart';

/// Every library the mined corpus imports, plus the near neighbours a future mine is
/// likely to bring in. A URI absent from the table is never dropped and never counts as
/// covering another import, so the table being incomplete is safe -- `dart_tools` reports
/// unknown URIs so they can be added here.
const libraries = <String>[
  'package:flutter/material.dart',
  'package:flutter/cupertino.dart',
  'package:flutter/widgets.dart',
  'package:flutter/painting.dart',
  'package:flutter/rendering.dart',
  'package:flutter/foundation.dart',
  'package:flutter/gestures.dart',
  'package:flutter/animation.dart',
  'package:flutter/scheduler.dart',
  'package:flutter/semantics.dart',
  'package:flutter/physics.dart',
  'package:flutter/services.dart',
  'dart:ui',
  'dart:math',
  'dart:async',
  'dart:collection',
  'dart:convert',
  'dart:typed_data',
  'dart:io',
  'dart:developer',
];

Future<void> main(List<String> args) async {
  if (args.isEmpty) {
    stderr.writeln('usage: dart run tool/export_namespaces.dart <project-root>');
    exitCode = 2;
    return;
  }
  final root = File(args.first).absolute.path;
  final collection = AnalysisContextCollection(includedPaths: [root]);
  final session = collection.contextFor(root).currentSession;

  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/export_namespaces.dart -- do not edit by hand.')
    ..writeln('//')
    ..writeln('// Dart SDK ${Platform.version.split(' ').first}. Regenerate after an SDK or')
    ..writeln('// Flutter upgrade; a stale table makes the import rule too conservative,')
    ..writeln('// never too aggressive.')
    ..writeln('library;')
    ..writeln()
    ..writeln('/// Exported top-level names, per library URI.')
    ..writeln('const exportedNames = <String, Set<String>>{');

  for (final uri in libraries) {
    final result = await session.getLibraryByUri(uri);
    if (result is! LibraryElementResult) {
      stderr.writeln('SKIPPED $uri -> ${result.runtimeType}');
      continue;
    }
    final names = result.element.exportNamespace.definedNames2.keys.toList()..sort();
    buffer.writeln("  '$uri': {");
    for (final name in names) {
      // Operators and other non-identifier entries can never be written as an identifier
      // reference in a transplant, so they cannot decide coverage either way.
      if (!RegExp(r'^[A-Za-z_$][A-Za-z0-9_$]*$').hasMatch(name)) continue;
      buffer.writeln("    '$name',");
    }
    buffer.writeln('  },');
  }
  buffer.writeln('};');
  stdout.write(buffer);
}
